// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReminderTelegramBot.WebApp.Data.Context;

#nullable disable

namespace ReminderTelegramBot.WebApp.Data.Migrations
{
    [DbContext(typeof(ReminderDbContext))]
    partial class ReminderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.14");

            modelBuilder.Entity("ReminderTelegramBot.WebApp.Data.Entities.Reminder", b =>
                {
                    b.Property<long>("ReminderKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RemindTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RemindTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramChatKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReminderKey");

                    b.HasIndex("TelegramChatKey");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("ReminderTelegramBot.WebApp.Data.Entities.TelegramChat", b =>
                {
                    b.Property<long>("TelegramChatKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TelegramChatKey");

                    b.ToTable("TelegramChats");
                });

            modelBuilder.Entity("ReminderTelegramBot.WebApp.Data.Entities.Reminder", b =>
                {
                    b.HasOne("ReminderTelegramBot.WebApp.Data.Entities.TelegramChat", "TelegramChat")
                        .WithMany("Reminders")
                        .HasForeignKey("TelegramChatKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelegramChat");
                });

            modelBuilder.Entity("ReminderTelegramBot.WebApp.Data.Entities.TelegramChat", b =>
                {
                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
